language: ruby
script: bundle exec rspec --color
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
notifications:
  webhooks: http://basho-engbot.herokuapp.com/travis?key=1a82cecc77a022b306b33d937403c8513578d1f3
  email: false
